@startuml
actor User
participant "Provisioning System" as pro
participant "OCS" as ocs
participant "SOI" as soi
participant "PCRF" as pcrf

User -> pro: Add Member HVC

alt OCS-Chia sẻ dữ liệu trong nhóm
else OCSAIR_communityAddMember_X
    alt
        else 1. Thêm thành viên nhóm
                pro -->ocs: OCSAIR_communityAddMember_X.OCSAIRU_UpdateCommunityList_Normal
        else 2. Link Offer cho thành viên nhóm
            pro -->ocs: OCSAIR_communityAddMember_X.OCSAIRU_UpdateOffer_Link
        else 3. Ecms Offer cho thành viên nhóm
                pro -->ocs: OCSAIR_communityAddMember_X.OCSAIRU_UpdateOffer_ECMS
        else 4. Reset UC cho thành viên nhóm
            pro -->ocs: OCSAIR_communityAddMember_X.OCSAIRU_UpdateUsageThresholdsAndCounters_ResetUC
        else 5. Set UT cho thuê bao thành viên
                pro -->ocs: OCSAIR_communityAddMember_X.OCSAIRU_UpdateUsageThresholdsAndCounters_SetUT
    end
end

alt PCRF-Chia sẻ dữ liệu trong nhóm
else Đăng ký thành viên vào nhóm
    pro -> pcrf: PCRF_communityDataShare_XforY.SetSAPCSubscription_register
end


pro --> User: Display data
@enduml
