@startuml
actor User
participant "Provisioning System" as pro
participant "OCS" as ocs
participant "SOI" as soi
participant "PCRF" as pcrf

User -> pro: Delete Member HVC

alt OCS-Chia sẻ dữ liệu trong nhóm
else OCSAIR_communityAddMember_X
    alt
        else 1. Link Offer cho thành viên nhóm
            pro -->ocs: OCSAIR_communityDeleteMember_X.OCSAIRA_DeleteOffer_NoProduct
        else 2. Ecms Offer cho thành viên nhóm
            pro -->ocs: OCSAIR_communityDeleteMember_X.OCSAIRA_DeleteOffer_NoProduct
        else 3. Reset UC cho thành viên nhóm
            pro -->ocs: OCSAIR_communityDeleteMember_X.OCSAIRU_UpdateUsageThresholdsAndCounters_ResetUC
        else 4. Huỷ thành viên nhóm
            pro -->ocs: OCSAIR_communityDeleteMember_X.OCSAIRU_UpdateCommunityList_DeleteMember
    end
end

alt PCRF-Chia sẻ dữ liệu trong nhóm
else Huỷ thành viên khỏi nhóm
    pro -> pcrf: PCRF_communityDataShare_XforY.SetSAPCSubscription_deregister
end
pro --> User: Display data
@enduml
